# Generated by Django 2.2.5 on 2019-11-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=100)),
                ('pack_type', models.CharField(max_length=100)),
                ('pack_price', models.IntegerField()),
                ('pack_summary', models.TextField(max_length=1000)),
            ],
        ),
    ]
