# Generated by Django 2.2.5 on 2019-11-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_pack_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('user_email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField()),
                ('adhaar_number', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">Adhaar number number</a>', max_length=13, verbose_name='ISBN')),
                ('pack_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookingapp.Pack_details')),
            ],
        ),
    ]
